//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int IdContract { get; set; }
        public int IdRequest { get; set; }
        public int IdVacancy { get; set; }
        public System.DateTime DateOfConclusion { get; set; }
        public Nullable<System.DateTime> BreakDate { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
