//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalActivity
    {
        public int IdEducationalActivity { get; set; }
        public int IdApplicant { get; set; }
        public int IdEducation { get; set; }
        public string NameEducationalnstitution { get; set; }
        public string Address { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Education Education { get; set; }
    }
}
