//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeLanguage
    {
        public int IdKnowledgeLanguage { get; set; }
        public int IdApplicant { get; set; }
        public int IdLanguage { get; set; }
        public int IdLanguageProficiency { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Language Language { get; set; }
        public virtual LanguageProficiency LanguageProficiency { get; set; }
    }
}
