//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaborActivity
    {
        public int IdLaborActivity { get; set; }
        public int IdApplicant { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationAddress { get; set; }
        public string ProfessionName { get; set; }
        public string Activity { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
