//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmploymentAgencyContext : DbContext
    {
        public EmploymentAgencyContext()
            : base("name=EmploymentAgencyContext")
        {
        }

        public EmploymentAgencyContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant> Applicant { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<DrivingLicenseCategory> DrivingLicenseCategory { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<EducationalActivity> EducationalActivity { get; set; }
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<EmploymentRequest> EmploymentRequest { get; set; }
        public virtual DbSet<EmploymentType> EmploymentType { get; set; }
        public virtual DbSet<Experience> Experience { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Industry> Industry { get; set; }
        public virtual DbSet<KnowledgeLanguage> KnowledgeLanguage { get; set; }
        public virtual DbSet<LaborActivity> LaborActivity { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<LanguageProficiency> LanguageProficiency { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<NecessarySkill> NecessarySkill { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<PossessionDrivingLicenseCategory> PossessionDrivingLicenseCategory { get; set; }
        public virtual DbSet<PossessionSkill> PossessionSkill { get; set; }
        public virtual DbSet<PreferredEmploymentType> PreferredEmploymentType { get; set; }
        public virtual DbSet<PreferredSchedule> PreferredSchedule { get; set; }
        public virtual DbSet<Profession> Profession { get; set; }
        public virtual DbSet<ProfessionCategory> ProfessionCategory { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<SubIndustry> SubIndustry { get; set; }
        public virtual DbSet<SuitableVacancy> SuitableVacancy { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vacancy> Vacancy { get; set; }
        public virtual DbSet<v_applicant> v_applicant { get; set; }
        public virtual DbSet<v_branch> v_branch { get; set; }
        public virtual DbSet<v_branchSimplifiedInformation> v_branchSimplifiedInformation { get; set; }
        public virtual DbSet<v_city> v_city { get; set; }
        public virtual DbSet<v_employer> v_employer { get; set; }
        public virtual DbSet<v_manager> v_manager { get; set; }
        public virtual DbSet<v_organization> v_organization { get; set; }
        public virtual DbSet<v_organizationWithoutPhoto> v_organizationWithoutPhoto { get; set; }
        public virtual DbSet<v_profession> v_profession { get; set; }
        public virtual DbSet<v_street> v_street { get; set; }
        public virtual DbSet<v_subIndustry> v_subIndustry { get; set; }
        public virtual DbSet<v_user> v_user { get; set; }
        public virtual DbSet<v_vacancy> v_vacancy { get; set; }
        public virtual DbSet<v_request> v_request { get; set; }
        public virtual DbSet<v_suitableVacancy> v_suitableVacancy { get; set; }
        public virtual DbSet<v_employmentRequest> v_employmentRequest { get; set; }
        public virtual DbSet<v_contract> v_contract { get; set; }
    }
}
