//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Employer = new HashSet<Employer>();
        }
    
        public int IdOrganization { get; set; }
        public int IdSubIndustry { get; set; }
        public string OrganizationName { get; set; }
        public byte[] Photo { get; set; }
        public int IdStreet { get; set; }
        public string NameHouse { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employer> Employer { get; set; }
        public virtual Street Street { get; set; }
        public virtual SubIndustry SubIndustry { get; set; }
    }
}
