//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossessionDrivingLicenseCategory
    {
        public int IdPossessionDrivingLicenseCategory { get; set; }
        public int IdApplicant { get; set; }
        public int IdDrivingLicenseCategory { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual DrivingLicenseCategory DrivingLicenseCategory { get; set; }
    }
}
