//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.PreferredEmploymentType = new HashSet<PreferredEmploymentType>();
            this.PreferredSchedule = new HashSet<PreferredSchedule>();
            this.SuitableVacancy = new HashSet<SuitableVacancy>();
        }
    
        public int IdRequest { get; set; }
        public int IdApplicant { get; set; }
        public int IdProfession { get; set; }
        public int IdExperience { get; set; }
        public string AboutMe { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public Nullable<System.DateTime> DateOfConsideration { get; set; }
        public int IdRequestStatus { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Experience Experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreferredEmploymentType> PreferredEmploymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreferredSchedule> PreferredSchedule { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuitableVacancy> SuitableVacancy { get; set; }
    }
}
