//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuitableVacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuitableVacancy()
        {
            this.EmploymentRequest = new HashSet<EmploymentRequest>();
        }
    
        public int IdSuitableVacancy { get; set; }
        public int IdRequest { get; set; }
        public int IdManager { get; set; }
        public int IdVacancy { get; set; }
        public System.DateTime DiscoveryDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentRequest> EmploymentRequest { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Request Request { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
