//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuitableVacancy
    {
        public int IdSuitableVacancy { get; set; }
        public int IdManager { get; set; }
        public int IdApplicant { get; set; }
        public int IdVacancy { get; set; }
        public System.DateTime DiscoveryDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
