//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_employer
    {
        public int IdEmployer { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string FullName { get; set; }
        public int IdGender { get; set; }
        public string GenderName { get; set; }
        public byte[] Photo { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public int IdOrganization { get; set; }
        public byte[] PhotoOrganization { get; set; }
        public string OrganizationName { get; set; }
        public int IdBranch { get; set; }
        public int IdCountry { get; set; }
        public string CountryName { get; set; }
        public int IdCity { get; set; }
        public string CityName { get; set; }
        public int IdStreet { get; set; }
        public string StreetName { get; set; }
        public string NameHouse { get; set; }
        public string AddressOrganization { get; set; }
    }
}
