//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_inDemandSkillsDetailedReport
    {
        public Nullable<System.DateTime> Date { get; set; }
        public int IdSkill { get; set; }
        public string SkillName { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Rate { get; set; }
    }
}
