//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_organizationWithoutPhoto
    {
        public int IdOrganization { get; set; }
        public int IdSubIndustry { get; set; }
        public string OrganizationName { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public int IdIndustry { get; set; }
    }
}
