//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_profession
    {
        public int IdProfession { get; set; }
        public int IdProfessionCategory { get; set; }
        public string NameProfessionCategory { get; set; }
        public string ProfessionName { get; set; }
    }
}
