//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_suitableVacancy
    {
        public int IdSuitableVacancy { get; set; }
        public int IdRequest { get; set; }
        public int IdApplicant { get; set; }
        public byte[] Photo { get; set; }
        public string ApplicantFullName { get; set; }
        public int IdGender { get; set; }
        public string GenderName { get; set; }
        public Nullable<int> Age { get; set; }
        public int IdCountry { get; set; }
        public string CountryName { get; set; }
        public int IdCity { get; set; }
        public string CityName { get; set; }
        public int IdStreet { get; set; }
        public string StreetName { get; set; }
        public string ApplicantAddress { get; set; }
        public string PhoneNumber { get; set; }
        public int IdExperience { get; set; }
        public string ExperienceName { get; set; }
        public Nullable<int> Salary { get; set; }
        public int IdVacancy { get; set; }
        public System.DateTime DiscoveryDate { get; set; }
    }
}
