//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentAgency.Model.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancy()
        {
            this.Contract = new HashSet<Contract>();
            this.NecessarySkill = new HashSet<NecessarySkill>();
            this.SuitableVacancy = new HashSet<SuitableVacancy>();
        }
    
        public int IdVacancy { get; set; }
        public int IdEmployer { get; set; }
        public int IdProfession { get; set; }
        public int IdEmploymentType { get; set; }
        public int IdSchedule { get; set; }
        public int IdExperience { get; set; }
        public string Description { get; set; }
        public string Duties { get; set; }
        public string Requirements { get; set; }
        public string Terms { get; set; }
        public Nullable<int> Salary { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual EmploymentType EmploymentType { get; set; }
        public virtual Experience Experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NecessarySkill> NecessarySkill { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuitableVacancy> SuitableVacancy { get; set; }
    }
}
